/*
 * Cinema reservation service
 * Micro service to buy cinema tickets and bar snacks.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.cinema.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.bp.cinema.model.PaymentCard;
import org.bp.cinema.model.Reservation;
/**
 * MovieReservationRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-20T22:53:52.011523+01:00[Europe/Warsaw]")
public class MovieReservationRequest {
  @JsonProperty("reservation")
  private Reservation reservation = null;

  @JsonProperty("paymentCard")
  private PaymentCard paymentCard = null;

  public MovieReservationRequest reservation(Reservation reservation) {
    this.reservation = reservation;
    return this;
  }

   /**
   * Get reservation
   * @return reservation
  **/

  public Reservation getReservation() {
    return reservation;
  }

  public void setReservation(Reservation reservation) {
    this.reservation = reservation;
  }

  public MovieReservationRequest paymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
    return this;
  }

   /**
   * Get paymentCard
   * @return paymentCard
  **/

  public PaymentCard getPaymentCard() {
    return paymentCard;
  }

  public void setPaymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieReservationRequest movieReservationRequest = (MovieReservationRequest) o;
    return Objects.equals(this.reservation, movieReservationRequest.reservation) &&
        Objects.equals(this.paymentCard, movieReservationRequest.paymentCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reservation, paymentCard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieReservationRequest {\n");
    
    sb.append("    reservation: ").append(toIndentedString(reservation)).append("\n");
    sb.append("    paymentCard: ").append(toIndentedString(paymentCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
