/*
 * Cinema reservation service
 * Micro service to buy cinema tickets and bar snacks.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.cinema.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.bp.cinema.model.Person;
import org.bp.cinema.model.Snack;
import org.bp.cinema.model.Ticket;
/**
 * Reservation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-20T22:53:52.011523+01:00[Europe/Warsaw]")
public class Reservation {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("ticket")
  private Ticket ticket = null;

  @JsonProperty("snack")
  private Snack snack = null;

  public Reservation(Person person2, Ticket ticket2, Snack snack2) {
	this.setPerson(person2);
	this.setSnack(snack2);
	this.setTicket(ticket2);
}

public Reservation person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/

  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public Reservation ticket(Ticket ticket) {
    this.ticket = ticket;
    return this;
  }

   /**
   * Get ticket
   * @return ticket
  **/

  public Ticket getTicket() {
    return ticket;
  }

  public void setTicket(Ticket ticket) {
    this.ticket = ticket;
  }

  public Reservation snack(Snack snack) {
    this.snack = snack;
    return this;
  }

   /**
   * Get snack
   * @return snack
  **/

  public Snack getSnack() {
    return snack;
  }

  public void setSnack(Snack snack) {
    this.snack = snack;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reservation reservation = (Reservation) o;
    return Objects.equals(this.person, reservation.person) &&
        Objects.equals(this.ticket, reservation.ticket) &&
        Objects.equals(this.snack, reservation.snack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, ticket, snack);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reservation {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    ticket: ").append(toIndentedString(ticket)).append("\n");
    sb.append("    snack: ").append(toIndentedString(snack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
