/*
 * Cinema reservation service
 * Micro service to buy cinema tickets and bar snacks.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.cinema.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import org.bp.cinema.model.Cinema;
import org.bp.cinema.model.Movie;
/**
 * Ticket
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-20T22:53:52.011523+01:00[Europe/Warsaw]")
public class Ticket {
  @JsonProperty("movie")
  private Movie movie = null;

  @JsonProperty("cinema")
  private Cinema cinema = null;

  @JsonProperty("seat")
  private String seat = null;

  @JsonProperty("time")
  private OffsetDateTime time = null;

  @JsonProperty("price")
  private Double price = null;

  public Ticket movie(Movie movie) {
    this.movie = movie;
    return this;
  }

   /**
   * Get movie
   * @return movie
  **/

  public Movie getMovie() {
    return movie;
  }

  public void setMovie(Movie movie) {
    this.movie = movie;
  }

  public Ticket cinema(Cinema cinema) {
    this.cinema = cinema;
    return this;
  }

   /**
   * Get cinema
   * @return cinema
  **/

  public Cinema getCinema() {
    return cinema;
  }

  public void setCinema(Cinema cinema) {
    this.cinema = cinema;
  }

  public Ticket seat(String seat) {
    this.seat = seat;
    return this;
  }

   /**
   * Get seat
   * @return seat
  **/

  public String getSeat() {
    return seat;
  }

  public void setSeat(String seat) {
    this.seat = seat;
  }

  public Ticket time(OffsetDateTime time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/

  public OffsetDateTime getTime() {
    return time;
  }

  public void setTime(OffsetDateTime time) {
    this.time = time;
  }

  public Ticket price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/

  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ticket ticket = (Ticket) o;
    return Objects.equals(this.movie, ticket.movie) &&
        Objects.equals(this.cinema, ticket.cinema) &&
        Objects.equals(this.seat, ticket.seat) &&
        Objects.equals(this.time, ticket.time) &&
        Objects.equals(this.price, ticket.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movie, cinema, seat, time, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ticket {\n");
    
    sb.append("    movie: ").append(toIndentedString(movie)).append("\n");
    sb.append("    cinema: ").append(toIndentedString(cinema)).append("\n");
    sb.append("    seat: ").append(toIndentedString(seat)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
