openapi: 3.0.1
info:
  title: Cinema reservation service
  description: Micro service to buy cinema tickets and bar snacks.
  contact:
    email: supportm@bp.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8090
tags:
- name: reservation
  description: Purchase ticket for your cinema experience
paths:
  '/reservation/{id}':
    get:
      tags:
      - reservation
      summary:  Get details of your seat reservation.
      description: Returns information about a person, ticket and a snack.
      operationId: getReservationById
      parameters:
      - name: id
        in: path
        description:  ID of reservation
        required: true
        schema: 
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieReservationInfo'
        400:
          description: Invalid ID supplied
        404:
          description: Reservation not found
      
  /reservation:
    post:
      tags:
      - reservation
      summary: Seat reservation for the movie.
      operationId: movieReserve
      requestBody:
        description: Details of seat reservation for the movie screening.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieReservationRequest'
        required: true
      responses:
        400:
          description: Problem during processing of your reservation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionResponse'    
      
    
components:
  schemas:
    Person:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
    Cinema:
      type: object
      properties:
        name:
          type: string
        city:
          type: string
        zip:
          type: string
    PaymentCard:
      type: object
      properties:
        name:
          type: string
        validTo:
          type: string
        number:
          type: string      
    MovieReservationInfo:
      type: object
      properties:
        id:
          type: string
        cost:
          type: number
          format: double
        reservation:
          $ref: '#/components/schemas/Reservation' 
        
    Movie:
      type: object
      properties:
        title:
          type: string
    
    Ticket:
      type: object
      properties:
        movie:
          $ref: '#/components/schemas/Movie'
        cinema:
          $ref: '#/components/schemas/Cinema'
        seat:
          type: string
        time:
          type: string
          format: date-time
        price:
          type: number
          format: double
    
    Snack:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: double 

    SnackRequest:
      type: object
      properties:
        person:
          $ref: '#/components/schemas/Person'
        snack:
          $ref: '#/components/schemas/Snack'
    
    TicketRequest:
      type: object
      properties:
        person:
          $ref: '#/components/schemas/Person'  
        ticket:
          $ref: '#/components/schemas/Ticket'     
    
    Reservation:
      type: object
      properties:
        person:
          $ref: '#/components/schemas/Person'
        ticket:
          $ref: '#/components/schemas/Ticket'
        snack:
          $ref: '#/components/schemas/Snack'
          
    MovieReservationRequest:
      type: object
      properties:
        reservation:
          $ref: '#/components/schemas/Reservation' 
        paymentCard:
          $ref: '#/components/schemas/PaymentCard'  
    ExceptionResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string

